import sys
c = open(sys.argv[1], 'r', encoding='utf-8').read()
c = c.replace('function execCmd(cmd, value) {', 'function execCmd(cmd: string, value?: string) {')
c = c.replace('function handleHeading(tag) {', 'function handleHeading(tag: string) {')
c = c.replace('function handleFontSize(size) {', 'function handleFontSize(size: string) {')
c = c.replace('function handleColor(color) {', 'function handleColor(color: string) {')
c = c.replace('function handleBgColor(color) {', 'function handleBgColor(color: string) {')
c = c.replace('function execCommand(cmd: string, value?: string) {\n    document.execCommand(cmd, false, value);\n    if (editorRef.current) editorRef.current.focus();\n  }', '')
c = c.replace('execCommand("bold"', 'execCmd("bold"')
c = c.replace('execCommand("italic"', 'execCmd("italic"')
c = c.replace('execCommand("underline"', 'execCmd("underline"')
c = c.replace('execCommand("justifyLeft"', 'execCmd("justifyLeft"')
c = c.replace('execCommand("justifyCenter"', 'execCmd("justifyCenter"')
c = c.replace('execCommand("justifyRight"', 'execCmd("justifyRight"')
c = c.replace('execCommand("insertUnorderedList"', 'execCmd("insertUnorderedList"')
c = c.replace('execCommand("insertOrderedList"', 'execCmd("insertOrderedList"')
c = c.replace('execCommand("undo"', 'execCmd("undo"')
c = c.replace('execCommand("redo"', 'execCmd("redo"')
c = c.replace('execCommand("strikeThrough"', 'execCmd("strikeThrough"')
c = c.replace('execCommand("removeFormat"', 'execCmd("removeFormat"')
c = c.replace('execCommand("insertHorizontalRule"', 'execCmd("insertHorizontalRule"')
c = c.replace('execCommand("fontSize"', 'execCmd("fontSize"')
c = c.replace('execCommand("foreColor"', 'execCmd("foreColor"')
c = c.replace('execCommand("hiliteColor"', 'execCmd("hiliteColor"')
c = c.replace('execCommand("insertHTML"', 'execCmd("insertHTML"')
c = c.replace('execCommand("createLink"', 'execCmd("createLink"')
c = c.replace('execCommand("styleWithCSS"', 'execCmd("styleWithCSS"')
c = c.replace('execCommand("insertImage", url)', 'execCmd("insertImage", url)')
c = c.replace('execCommand("formatBlock", "<blockquote>")', 'execCmd("formatBlock","<blockquote>")')
c = c.replace('execCommand("formatBlock", "<pre>")', 'execCmd("formatBlock","<pre>")')
import re
lines = c.split('\n')
seen = set()
result = []
for line in lines:
    s = line.strip()
    if s.startswith('function ') and not any(x in s for x in ['execCmd','ToolBtn','ToolDivider','TreeNode','SubToggle','handleTreeSelect','scheduleSave','handleTitleChange','handleEditorInput','handleCreate']):
        name = s.split('(')[0].replace('function ','').strip()
        if name in seen: continue
        seen.add(name)
    result.append(line)
c = '\n'.join(result)
open(sys.argv[1], 'w', encoding='utf-8').write(c)
print('Fixed and written')