import sys
c = open(sys.argv[1], 'r', encoding='utf-8').read()
c = c.replace('execCommand("bold")', 'execCmd("bold")')
c = c.replace('execCommand("italic")', 'execCmd("italic")')
c = c.replace('execCommand("underline")', 'execCmd("underline")')
c = c.replace('execCommand("strikeThrough")', 'execCmd("strikeThrough")')
c = c.replace('execCommand("justifyLeft")', 'execCmd("justifyLeft")')
c = c.replace('execCommand("justifyCenter")', 'execCmd("justifyCenter")')
c = c.replace('execCommand("justifyRight")', 'execCmd("justifyRight")')
c = c.replace('execCommand("insertUnorderedList")', 'execCmd("insertUnorderedList")')
c = c.replace('execCommand("insertOrderedList")', 'execCmd("insertOrderedList")')
c = c.replace('execCommand("undo")', 'execCmd("undo")')
c = c.replace('execCommand("redo")', 'execCmd("redo")')
c = c.replace('execCommand("removeFormat")', 'execCmd("removeFormat")')
c = c.replace('execCommand("insertHorizontalRule")', 'execCmd("insertHorizontalRule")')
c = c.replace('execCommand("formatBlock", "<blockquote>")', 'execCmd("formatBlock","<blockquote>")')
c = c.replace('execCommand("formatBlock", "<pre>")', 'execCmd("formatBlock","<pre>")')
c = c.replace('execCommand("formatBlock", "<h1>")', 'execCmd("formatBlock","<h1>")')
c = c.replace('execCommand("formatBlock", "<h2>")', 'execCmd("formatBlock","<h2>")')
c = c.replace('execCommand("formatBlock", "<h3>")', 'execCmd("formatBlock","<h3>")')
open(sys.argv[1], 'w', encoding='utf-8').write(c)
print('OK')